
module PandocRb
  Writers = [ "asciidoc",
              "beamer",
              "commonmark",
              "context",
              "docbook",
              "docbook5",
              "docx",
              "dokuwiki",
              "dzslides",
              "epub",
              "epub3",
              "fb2",
              "haddock",
              "html",
              "html5",
              "icml",
              "json",
              "latex",
              "man",
              "markdown",
              "markdown_github",
              "markdown_mmd",
              "markdown_phpextra",
              "markdown_strict",
              "mediawiki",
              "native",
              "odt",
              "opendocument",
              "opml",
              "org",
              "plain",
              "revealjs",
              "rst",
              "rtf",
              "s5",
              "slideous",
              "slidy",
              "tei",
              "texinfo",
              "textile",
              "zimwiki"
            ]
end

